package main

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"strings"
	"time"
)

// This is our interface, allowing us to enable proper testing
type BackgroundProcessor interface {
	processAutoOcrTagDocuments(ctx context.Context) (int, error)
	processAutoTagDocuments(ctx context.Context) (int, error)
	isOcrEnabled() bool
}

// Start our background tasks in a goroutine
func StartBackgroundTasks(ctx context.Context, app BackgroundProcessor) {
	go func() {
		minBackoffDuration := 10 * time.Second
		maxBackoffDuration := time.Hour
		pollingInterval := 10 * time.Second

		backoffDuration := minBackoffDuration

		for {
			select {
			case <-ctx.Done():
				log.Infoln("Background tasks shutting down")
				return
			default: // needed to make this non-blocking
			}

			processedCount, err := func() (count int, err error) {
				count = 0

				// If OCR is enabled, run OCR tagging first
				if app.isOcrEnabled() {
					ocrCount, err := app.processAutoOcrTagDocuments(ctx)
					if err != nil {
						return 0, fmt.Errorf("error in processAutoOcrTagDocuments: %w", err)
					}
					count += ocrCount
				}

				// Run auto-tagging after OCR
				autoCount, err := app.processAutoTagDocuments(ctx)
				if err != nil {
					return 0, fmt.Errorf("error in processAutoTagDocuments: %w", err)
				}
				count += autoCount

				return count, nil
			}()

			if err != nil {
				log.Errorf("Error in background tagging: %v", err)
				time.Sleep(backoffDuration)

				// Exponential backoff logic
				backoffDuration *= 2
				if backoffDuration > maxBackoffDuration {
					log.Warnf("Max backoff duration reached. Using %v", maxBackoffDuration)
					backoffDuration = maxBackoffDuration
				}
			} else {
				// Reset backoff when processing succeeds
				backoffDuration = minBackoffDuration
			}

			// If nothing was processed, pause before next cycle
			if processedCount == 0 {
				time.Sleep(pollingInterval)
			}
		}
	}()
}

// processAutoTagDocuments handles the background auto-tagging of documents
func (app *App) processAutoTagDocuments(ctx context.Context) (int, error) {
	documents, err := app.Client.GetDocumentsByTag(ctx, autoTag, 25)
	if err != nil {
		return 0, fmt.Errorf("error fetching documents with autoTag: %w", err)
	}

	if len(documents) == 0 {
		log.Debugf("No documents with tag %s found", autoTag)
		return 0, nil // No documents to process
	}

	// Refresh the custom fields cache before processing, as we have documents
	refreshCustomFieldsCache(app.Client)

	log.Debugf("Found at least %d remaining documents with tag %s", len(documents), autoTag)

	var errs []error
	processedCount := 0

	for _, docSummary := range documents {
		// Get the full document details, including custom fields
		document, err := app.Client.GetDocument(ctx, docSummary.ID)
		if err != nil {
			err = fmt.Errorf("error fetching full details for document %d: %w", docSummary.ID, err)
			documentLogger(docSummary.ID).Error(err.Error())
			errs = append(errs, err)
			continue
		}

		// Skip documents that have the autoOcrTag
		if slices.Contains(document.Tags, autoOcrTag) {
			log.Debugf("Skipping document %d as it has the OCR tag %s", document.ID, autoOcrTag)
			continue
		}

		docLogger := documentLogger(document.ID)

		// Check if this document has exceeded max retries
		if app.Database != nil {
			failure, dbErr := GetDocumentFailure(app.Database, document.ID)
			if dbErr != nil {
				docLogger.Errorf("Error checking failure count: %v", dbErr)
			}
			if failure != nil && failure.FailureCount >= documentMaxRetries {
				// Check if cooldown period has elapsed for auto-retry
				if documentRetryAfter > 0 && time.Since(failure.LastFailedAt) >= documentRetryAfter {
					docLogger.Infof("Document failed %d times but cooldown of %v has elapsed, retrying",
						failure.FailureCount, documentRetryAfter)
					ResetDocumentFailure(app.Database, document.ID)
					// Fall through to normal processing
				} else {
					docLogger.Warnf("Document has failed %d times (max %d), marking as failed",
						failure.FailureCount, documentMaxRetries)
					markErr := app.Client.UpdateDocuments(ctx, []DocumentSuggestion{
						{
							ID:               document.ID,
							OriginalDocument: document,
							RemoveTags:       []string{autoTag},
							AddTags:          []string{failedTag},
						},
					}, app.Database, false)
					if markErr != nil {
						docLogger.Errorf("Failed to mark document as failed: %v", markErr)
						errs = append(errs, markErr)
					}
					continue
				}
			}
		}

		docLogger.Info("Processing document for auto-tagging")

		suggestionRequest := GenerateSuggestionsRequest{
			Documents:              []Document{document},
			GenerateTitles:         strings.ToLower(autoGenerateTitle) != "false",
			GenerateTags:           strings.ToLower(autoGenerateTags) != "false",
			GenerateCorrespondents: strings.ToLower(autoGenerateCorrespondents) != "false",
			GenerateDocumentTypes:  strings.ToLower(autoGenerateDocumentType) != "false",
			GenerateCreatedDate:    strings.ToLower(autoGenerateCreatedDate) != "false",
			GenerateCustomFields:   settings.CustomFieldsEnable,
		}

		suggestions, err := app.generateDocumentSuggestions(ctx, suggestionRequest, docLogger)
		if err != nil {
			err = fmt.Errorf("error generating suggestions for document %d: %w", document.ID, err)
			docLogger.Error(err.Error())
			if app.Database != nil {
				count, dbErr := IncrementDocumentFailure(app.Database, document.ID, err.Error())
				if dbErr != nil {
					docLogger.Errorf("Failed to record failure: %v", dbErr)
				}
				docLogger.Warnf("Document failure count: %d/%d", count, documentMaxRetries)
			}
			errs = append(errs, err)
			continue
		}

		// Remove the processing tags after auto-tagging completes
		for i := range suggestions {
			suggestions[i].RemoveTags = append(suggestions[i].RemoveTags, autoTag)
			if app.pdfOCRCompleteTag != "" {
				suggestions[i].RemoveTags = append(suggestions[i].RemoveTags, app.pdfOCRCompleteTag)
			}
		}

		err = app.Client.UpdateDocuments(ctx, suggestions, app.Database, false)
		if err != nil {
			err = fmt.Errorf("error updating document %d: %w", document.ID, err)
			docLogger.Error(err.Error())
			if app.Database != nil {
				count, dbErr := IncrementDocumentFailure(app.Database, document.ID, err.Error())
				if dbErr != nil {
					docLogger.Errorf("Failed to record failure: %v", dbErr)
				}
				docLogger.Warnf("Document failure count: %d/%d", count, documentMaxRetries)
			}
			errs = append(errs, err)
			continue
		}

		// Reset failure count on success
		if app.Database != nil {
			ResetDocumentFailure(app.Database, document.ID)
		}
		docLogger.Info("Successfully processed document")
		processedCount++
	}

	if len(errs) > 0 {
		return processedCount, errors.Join(errs...)
	}

	return processedCount, nil
}

// processAutoOcrTagDocuments handles the background auto-tagging of OCR documents
func (app *App) processAutoOcrTagDocuments(ctx context.Context) (int, error) {
	documents, err := app.Client.GetDocumentsByTag(ctx, autoOcrTag, 25)
	if err != nil {
		return 0, fmt.Errorf("error fetching documents with autoOcrTag: %w", err)
	}

	if len(documents) == 0 {
		log.Debugf("No documents with tag %s found", autoOcrTag)
		return 0, nil
	}

	log.Debugf("Found %d documents with tag %s", len(documents), autoOcrTag)

	successCount := 0
	var errs []error

	for _, document := range documents {
		docLogger := documentLogger(document.ID)

		// Check if this document has exceeded max retries
		if app.Database != nil {
			failure, dbErr := GetDocumentFailure(app.Database, document.ID)
			if dbErr != nil {
				docLogger.Errorf("Error checking failure count: %v", dbErr)
			}
			if failure != nil && failure.FailureCount >= documentMaxRetries {
				// Check if cooldown period has elapsed for auto-retry
				if documentRetryAfter > 0 && time.Since(failure.LastFailedAt) >= documentRetryAfter {
					docLogger.Infof("Document failed %d times but cooldown of %v has elapsed, retrying",
						failure.FailureCount, documentRetryAfter)
					ResetDocumentFailure(app.Database, document.ID)
					// Fall through to normal processing
				} else {
					docLogger.Warnf("Document has failed %d times (max %d), marking as failed",
						failure.FailureCount, documentMaxRetries)
					markErr := app.Client.UpdateDocuments(ctx, []DocumentSuggestion{
						{
							ID:               document.ID,
							OriginalDocument: document,
							RemoveTags:       []string{autoOcrTag},
							AddTags:          []string{failedTag},
						},
					}, app.Database, false)
					if markErr != nil {
						docLogger.Errorf("Failed to mark document as failed: %v", markErr)
						errs = append(errs, markErr)
					}
					continue
				}
			}
		}

		docLogger.Info("Processing document for OCR")

		// Skip OCR if the document already has the OCR complete tag and tagging is enabled
		if app.pdfOCRTagging {
			hasCompleteTag := false
			for _, tag := range document.Tags {
				if tag == app.pdfOCRCompleteTag {
					hasCompleteTag = true
					break
				}
			}

			if hasCompleteTag {
				docLogger.Infof("Document already has OCR complete tag '%s', skipping OCR processing", app.pdfOCRCompleteTag)

				// Remove only the autoOcrTag to take it out of the processing queue
				// while preserving the OCR complete tag
				err = app.Client.UpdateDocuments(ctx, []DocumentSuggestion{
					{
						ID:               document.ID,
						OriginalDocument: document,
						RemoveTags:       []string{autoOcrTag},
					},
				}, app.Database, false)

				if err != nil {
					docLogger.Errorf("Update to remove autoOcrTag failed: %v", err)
					errs = append(errs, fmt.Errorf("document %d update error: %w", document.ID, err))
					continue
				}

				docLogger.Info("Successfully removed auto OCR tag")
				successCount++
				continue
			}
		}

		options := OCROptions{
			UploadPDF:       app.pdfUpload,
			ReplaceOriginal: app.pdfReplace,
			CopyMetadata:    app.pdfCopyMetadata,
			LimitPages:      limitOcrPages,
			ProcessMode:     app.ocrProcessMode,
		}

		// Use the DocumentProcessor interface instead of calling the method directly
		var processedDoc *ProcessedDocument
		var err error
		if app.docProcessor != nil {
			// Use injected processor if available
			processedDoc, err = app.docProcessor.ProcessDocumentOCR(ctx, document.ID, options, "")
		} else {
			// Use the app's own implementation if no processor is injected
			processedDoc, err = app.ProcessDocumentOCR(ctx, document.ID, options, "")
		}

		if err != nil {
			docLogger.Errorf("OCR processing failed: %v", err)
			if app.Database != nil {
				count, dbErr := IncrementDocumentFailure(app.Database, document.ID, err.Error())
				if dbErr != nil {
					docLogger.Errorf("Failed to record failure: %v", dbErr)
				}
				docLogger.Warnf("Document failure count: %d/%d", count, documentMaxRetries)
			}
			errs = append(errs, fmt.Errorf("document %d OCR error: %w", document.ID, err))
			continue
		}
		if processedDoc == nil {
			docLogger.Info("OCR processing skipped for document")
			continue
		}
		docLogger.Debug("OCR processing completed")

		documentSuggestion := DocumentSuggestion{
			ID:               document.ID,
			OriginalDocument: document,
			SuggestedContent: processedDoc.Text,
			RemoveTags:       []string{autoOcrTag},
			// Add OCR complete tag if tagging is enabled and PDF wasn't uploaded (upload handles tagging)
			AddTags: func() []string {
				if app.pdfOCRTagging && !options.UploadPDF {
					return []string{app.pdfOCRCompleteTag}
				}
				return nil
			}(),
		}

		if (app.pdfOCRTagging) && app.pdfOCRCompleteTag != "" {
			// Add the OCR complete tag if tagging is enabled
			documentSuggestion.SuggestedTags = []string{app.pdfOCRCompleteTag}
			documentSuggestion.KeepOriginalTags = true
			docLogger.Infof("Adding OCR complete tag '%s'", app.pdfOCRCompleteTag)
		}

		// Skip updating the original document if it was actually replaced (deleted) during OCR.
		// The replacement document will be processed as a new document on the next cycle.
		if options.ReplaceOriginal && processedDoc != nil && processedDoc.ReplacedOriginal {
			docLogger.Info("Skipping tag update for replaced document (original was deleted)")
		} else {
			err = app.Client.UpdateDocuments(ctx, []DocumentSuggestion{
				documentSuggestion,
			}, app.Database, false)
			if err != nil {
				docLogger.Errorf("Update after OCR failed: %v", err)
				errs = append(errs, fmt.Errorf("document %d update error: %w", document.ID, err))
				continue
			}
		}

		// Reset failure count on success
		if app.Database != nil {
			ResetDocumentFailure(app.Database, document.ID)
		}
		docLogger.Info("Successfully processed document OCR")
		successCount++
	}

	if len(errs) > 0 {
		return successCount, fmt.Errorf("one or more errors occurred: %w", errors.Join(errs...))
	}

	return successCount, nil
}
